- name: getting parameters from aws 
  hosts: localhost
  tasks:
    - name: getting parameter from aws
      ansible.builtin.debug: 
        msg= "{{ lookup('amazon.aws.aws_ssm', 'sai', region='us-east-1' ) }}"
